site_name: Weasley Docs
pages:
- Home: index.md
- CodeTime:
    - JavaWeb: JavaWeb.md
    - iOS:
        - CocoaPod: how_to_use_cocoapod.md
        - Component: common_use_components.md
        - blogs: iOSReference/ios_blogs.md
    - TODOList: iOSReference/ios_todo.md
    - Tips: 
            - iOSReference/iOSTips.md
            - iOSReference/ios_view_alpha.md
            - macVPN_divert.md
- OutOfWork:
    - Accounting:
        - accounting/accountingBase_ch1.md
        - accounting/accountingBase_ch2.md
        - accounting/accountingBase_ch3.md
    - ReadingThoughts:
        - 转型之战：传统互企业的互联网机会: traditional_enterprise_in_internet.md
        - 社交红利: traditional_enterprise_in_internet.md
        - Zero2One: from0to1.md
- ETime:
    - Resources: Superb_English_sites.md
    - ED:
        - ED/201601/20160104.md
        - ED/201601/20160105.md
        - ED/201601/20160106.md
        - ED/201601/20160107.md
- About: about.md